#!/usr/bin/env python3
"""validate_xlsx.py - Excel-strict validation and repair for BDM workbooks.

WHY THIS EXISTS
---------------
When a controlled BDM template is populated by splicing <sheetData> back into the
original worksheet bytes (the technique used to preserve the anchored BDM logo,
styles and headers), three things go stale that Excel checks on open and that
NEITHER openpyxl NOR LibreOffice look at:

  1. xl/calcChain.xml     - a precomputed dependency list naming every formula
                            cell.  Turn a formula cell into a value cell and the
                            chain still names it.  Excel walks the chain on open,
                            finds an entry with no formula, and reports
                            "unreadable content" / offers to repair.
                            THIS IS THE #1 CAUSE OF "CORRUPTED" BDM WORKBOOKS.
  2. <dimension ref>      - the declared used range.  Append rows past it and the
                            sheet under-reports its extent.
  3. shared formulas      - replace the MASTER cell of a shared-formula group
                            (<f t="shared" ref=".." si="N">) and every dependent
                            cell references an si that no longer has a master.

openpyxl ignores all three; LibreOffice rebuilds them silently on convert.  So a
workbook can pass an openpyxl load AND a LibreOffice recalc and still be dead in
Excel.  Never certify a workbook off either of those alone.

USAGE
-----
    python3 validate_xlsx.py --check  book.xlsx [more.xlsx ...]
    python3 validate_xlsx.py --repair book.xlsx [more.xlsx ...]   # fixes 1 and 2 in place

    from validate_xlsx import check, repair
    errs = check(path)          # [] means clean
    repair(path)                # then check() again - it must come back clean

--repair drops xl/calcChain.xml entirely (plus its content-type override and its
relationship).  Excel rebuilds the chain on open; the file is smaller and correct.
It does NOT touch cell values, formulas, styles, drawings or media.

RULE: run --repair then --check on every workbook before it is handed over.
A workbook that has not been through this has not been verified.
"""
import re
import shutil
import sys
import zipfile

from lxml import etree

NS = '{http://schemas.openxmlformats.org/spreadsheetml/2006/main}'
PR = '{http://schemas.openxmlformats.org/package/2006/relationships}'
CT = '{http://schemas.openxmlformats.org/package/2006/content-types}'
MC = '{http://schemas.openxmlformats.org/markup-compatibility/2006}'
SHEET_RE = re.compile(r'xl/worksheets/sheet\d+\.xml$')


def _col_letter(n):
    s = ''
    while n:
        n, r = divmod(n - 1, 26)
        s = chr(65 + r) + s
    return s


def _col_idx(c):
    n = 0
    for ch in c:
        n = n * 26 + (ord(ch) - 64)
    return n


def _used_range(ws):
    refs = [c.get('r') for c in ws.iter(NS + 'c') if c.get('r')]
    if not refs:
        return None
    rows = [int(re.match(r'[A-Z]+(\d+)', r).group(1)) for r in refs]
    cols = [_col_idx(re.match(r'([A-Z]+)', r).group(1)) for r in refs]
    return f'{_col_letter(min(cols))}{min(rows)}:{_col_letter(max(cols))}{max(rows)}'


def check(path):
    """Return a list of defects. Empty list = clean."""
    e = []
    z = zipfile.ZipFile(path)
    names = z.namelist()

    # --- package integrity -------------------------------------------------
    for n in names:
        if not n.endswith(('.xml', '.rels')):
            continue
        try:
            root = etree.fromstring(z.read(n))
        except Exception as ex:
            e.append(f'XML PARSE {n}: {ex}')
            continue
        for pre in (root.get(MC + 'Ignorable') or '').split():
            if pre not in root.nsmap:
                e.append(f'{n}: mc:Ignorable names undeclared prefix "{pre}" '
                         f'(Excel will call the file corrupt)')
        for pre in (root.nsmap or {}):
            if pre and re.fullmatch(r'ns\d+', pre) and not n.startswith('customXml/'):
                e.append(f'{n}: autogenerated namespace prefix {pre} - a whole '
                         f'worksheet part was re-serialised; splice <sheetData> only')

    ct = etree.fromstring(z.read('[Content_Types].xml'))
    for o in ct.iter(CT + 'Override'):
        if o.get('PartName').lstrip('/') not in names:
            e.append(f'content-type override points at missing part {o.get("PartName")}')

    for n in names:
        if not n.endswith('.rels'):
            continue
        base = '' if n == '_rels/.rels' else n.replace('_rels/', '').rsplit('/', 1)[0]
        for r in etree.fromstring(z.read(n)):
            t = r.get('Target')
            if r.get('TargetMode') == 'External' or t.startswith('http'):
                continue
            tgt = '/'.join(x for x in (base, t) if x) if not t.startswith('/') else t.lstrip('/')
            tgt = re.sub(r'[^/]+/\.\./', '', tgt).lstrip('/')
            if tgt not in names:
                e.append(f'{n}: dangling relationship -> {t}')

    if not [n for n in names if n.startswith('xl/media/')]:
        e.append('xl/media/ is empty - the anchored BDM logo has been stripped. '
                 'Do not hand this over; rebuild by splicing, not via openpyxl save.')

    # --- the three Excel-strict checks openpyxl and LibreOffice cannot see --
    if 'xl/calcChain.xml' in names:
        chain = [(c.get('r'), c.get('i')) for c in etree.fromstring(z.read('xl/calcChain.xml'))]
        for sn in filter(SHEET_RE.match, names):
            ws = etree.fromstring(z.read(sn))
            sid = re.search(r'sheet(\d+)', sn).group(1)
            formulas = {c.get('r') for c in ws.iter(NS + 'c') if c.find(NS + 'f') is not None}
            stale = {r for r, i in chain if i == sid} - formulas
            if stale:
                e.append(f'STALE calcChain in {sn}: {len(stale)} cells listed in the calc '
                         f'chain no longer hold a formula, e.g. {sorted(stale)[:6]}. '
                         f'EXCEL WILL REPORT THIS FILE AS CORRUPT. Run --repair.')

    for sn in filter(SHEET_RE.match, names):
        ws = etree.fromstring(z.read(sn))

        masters, deps = {}, []
        for c in ws.iter(NS + 'c'):
            f = c.find(NS + 'f')
            if f is None or f.get('t') != 'shared':
                continue
            if f.get('ref') is not None and (f.text or '').strip():
                masters.setdefault(f.get('si'), c.get('r'))
            else:
                deps.append((f.get('si'), c.get('r')))
        orphans = [d for d in deps if d[0] not in masters]
        if orphans:
            e.append(f'ORPHAN shared formulas in {sn}: {orphans[:6]} - the master cell of a '
                     f'shared-formula group was overwritten. Write the full formula into '
                     f'every member of the group instead.')

        d = ws.find(NS + 'dimension')
        actual = _used_range(ws)
        if d is not None and actual and d.get('ref') != actual:
            declared_max = int(re.search(r'(\d+)$', d.get('ref').split(':')[-1]).group(1))
            actual_max = int(re.search(r'(\d+)$', actual).group(1))
            if actual_max > declared_max:
                e.append(f'STALE dimension in {sn}: declares {d.get("ref")} but data runs to '
                         f'{actual}. Run --repair.')

        refs = [c.get('r') for c in ws.iter(NS + 'c') if c.get('r')]
        if len(refs) != len(set(refs)):
            dupes = sorted({r for r in refs if refs.count(r) > 1})[:6]
            e.append(f'DUPLICATE cell references in {sn}: {dupes}')

        for row in ws.iter(NS + 'row'):
            rn = row.get('r')
            bad = [c.get('r') for c in row.findall(NS + 'c')
                   if not re.fullmatch(rf'[A-Z]+{rn}', c.get('r') or '')]
            if bad:
                e.append(f'{sn}: cell placed in the wrong row {rn}: {bad[:4]}')

        for c in ws.iter(NS + 'c'):
            if c.get('t') == 'inlineStr' and c.find(NS + 'is') is None:
                e.append(f'{sn} {c.get("r")}: t="inlineStr" with no <is> child')

    try:
        import openpyxl
        openpyxl.load_workbook(path)
    except Exception as ex:
        e.append(f'openpyxl could not load the file: {ex}')

    return e


def repair(path):
    """Drop the stale calcChain and correct every stale <dimension>. In place."""
    z = zipfile.ZipFile(path)
    names = [n for n in z.namelist() if not n.endswith('/')]
    out, drop, fixed = {}, set(), []

    if 'xl/calcChain.xml' in names:
        drop.add('xl/calcChain.xml')
        ct = etree.fromstring(z.read('[Content_Types].xml'))
        for o in list(ct.findall(CT + 'Override')):
            if o.get('PartName') == '/xl/calcChain.xml':
                ct.remove(o)
        out['[Content_Types].xml'] = etree.tostring(
            ct, xml_declaration=True, encoding='UTF-8', standalone=True)
        rl = etree.fromstring(z.read('xl/_rels/workbook.xml.rels'))
        for r in list(rl.findall(PR + 'Relationship')):
            if r.get('Target', '').endswith('calcChain.xml'):
                rl.remove(r)
        out['xl/_rels/workbook.xml.rels'] = etree.tostring(
            rl, xml_declaration=True, encoding='UTF-8', standalone=True)

    for n in filter(SHEET_RE.match, names):
        raw = z.read(n)
        actual = _used_range(etree.fromstring(raw))
        if not actual:
            continue
        m = re.search(rb'<dimension\s+ref="([^"]*)"\s*/>', raw)
        if m and m.group(1).decode() != actual:
            out[n] = raw[:m.start()] + f'<dimension ref="{actual}"/>'.encode() + raw[m.end():]
            fixed.append(n)

    # force a full recalculation so the dropped chain is rebuilt correctly
    wb = z.read('xl/workbook.xml')
    if b'fullCalcOnLoad="1"' not in wb:
        wb = (re.sub(rb'<calcPr\b[^>]*/>', b'<calcPr calcId="0" fullCalcOnLoad="1"/>', wb)
              if b'<calcPr' in wb else
              wb.replace(b'</workbook>', b'<calcPr calcId="0" fullCalcOnLoad="1"/></workbook>'))
        out['xl/workbook.xml'] = wb

    if not out and not drop:
        return 'nothing to repair'

    tmp = path + '.repairtmp'
    with zipfile.ZipFile(tmp, 'w', zipfile.ZIP_DEFLATED) as w:
        for n in names:
            if n in drop:
                continue
            w.writestr(z.getinfo(n), out.get(n, z.read(n)))
    z.close()
    shutil.move(tmp, path)
    bits = []
    if drop:
        bits.append('removed stale xl/calcChain.xml')
    if fixed:
        bits.append(f'corrected <dimension> on {len(fixed)} sheet(s)')
    return '; '.join(bits)


def main():
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    do_repair = '--repair' in sys.argv
    if not args:
        sys.exit(__doc__)
    bad = False
    for p in args:
        name = p.rsplit('/', 1)[-1].rsplit('\\', 1)[-1]
        if do_repair:
            print(f'{name}\n  REPAIR: {repair(p)}')
        errs = check(p)
        if errs:
            bad = True
            print(f'{name}\n  ' + '\n  '.join(errs))
        else:
            print(f'{name}\n  CLEAN - safe to hand over')
    sys.exit(1 if bad else 0)


if __name__ == '__main__':
    main()
